# Auto-generated by gen_android_bp.py for hda symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_hda_conf_d_HDA_Intel_HDA_Intel_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_hda.mk
	@echo "Symlink: alsa_ucm_conf_hda_conf_d_HDA_Intel_HDA_Intel_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/HDA-Intel
	ln -sf ../../HDA/HDA.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/HDA-Intel/HDA-Intel.conf
	touch $@

