# Auto-generated by gen_android_bp.py

LOCAL_PATH := $(call my-dir)

include $(LOCAL_PATH)/Android_allwinner.mk
include $(LOCAL_PATH)/Android_amd.mk
include $(LOCAL_PATH)/Android_amlogic.mk
include $(LOCAL_PATH)/Android_common.mk
include $(LOCAL_PATH)/Android_hda.mk
include $(LOCAL_PATH)/Android_intel.mk
include $(LOCAL_PATH)/Android_io-boards.mk
include $(LOCAL_PATH)/Android_mediatek.mk
include $(LOCAL_PATH)/Android_nxp.mk
include $(LOCAL_PATH)/Android_omap.mk
include $(LOCAL_PATH)/Android_qualcomm.mk
include $(LOCAL_PATH)/Android_rockchip.mk
include $(LOCAL_PATH)/Android_samsung.mk
include $(LOCAL_PATH)/Android_sof-soundwire.mk
include $(LOCAL_PATH)/Android_tegra.mk
include $(LOCAL_PATH)/Android_usb-audio.mk
