# Auto-generated by gen_android_bp.py for amd symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_amd_conf_d_acp3x_es83xx_acp3x_es83xx_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_amd.mk
	@echo "Symlink: alsa_ucm_conf_amd_conf_d_acp3x_es83xx_acp3x_es83xx_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp3x-es83xx
	ln -sf ../../AMD/acp3x-es83xx/acp3x-es83xx.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp3x-es83xx/acp3x-es83xx.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_amd_conf_d_acp3xalc5682m98_acp3xalc5682m98_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_amd.mk
	@echo "Symlink: alsa_ucm_conf_amd_conf_d_acp3xalc5682m98_acp3xalc5682m98_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp3xalc5682m98
	ln -sf ../../AMD/acp3x-alc5682-max98357/acp3x-alc5682-max98357.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp3xalc5682m98/acp3xalc5682m98.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_amd_conf_d_acpd7219m98357_acpd7219m98357_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_amd.mk
	@echo "Symlink: alsa_ucm_conf_amd_conf_d_acpd7219m98357_acpd7219m98357_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acpd7219m98357
	ln -sf ../../AMD/acp-da7219-rt5682-max98357/acp-da7219-rt5682-max98357.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acpd7219m98357/acpd7219m98357.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_amd_conf_d_acp3xalc5682101_acp3xalc5682101_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_amd.mk
	@echo "Symlink: alsa_ucm_conf_amd_conf_d_acp3xalc5682101_acp3xalc5682101_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp3xalc5682101
	ln -sf ../../AMD/acp3x-alc5682-alc1015/acp3x-alc5682-alc1015.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp3xalc5682101/acp3xalc5682101.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_amd_conf_d_acp5x_Valve_Jupiter_1_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_amd.mk
	@echo "Symlink: alsa_ucm_conf_amd_conf_d_acp5x_Valve_Jupiter_1_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp5x
	ln -sf ../../AMD/acp5x/acp5x.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp5x/Valve-Jupiter-1.conf
	touch $@

