# Auto-generated by gen_android_bp.py for qualcomm symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_module_snd_soc_sdm845_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_module_snd_soc_sdm845_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module
	ln -sf ../Qualcomm/sdm845/sdm845.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module/snd_soc_sdm845.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_module_snd_soc_apq8096_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_module_snd_soc_apq8096_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module
	ln -sf ../Qualcomm/apq8096/apq8096.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module/snd_soc_apq8096.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_module_snd_soc_apq8016_sbc_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_module_snd_soc_apq8016_sbc_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module
	ln -sf ../Qualcomm/apq8016-sbc/apq8016-sbc.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module/snd_soc_apq8016_sbc.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_glymur_GLYMUR_CRD_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_glymur_GLYMUR_CRD_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/glymur
	ln -sf ../../Qualcomm/glymur/GLYMUR-CRD.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/glymur/GLYMUR-CRD.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_sm8750_SM8750_MTP_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_sm8750_SM8750_MTP_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sm8750
	ln -sf ../../Qualcomm/sm8750/MTP/SM8750-MTP.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sm8750/SM8750-MTP.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_sdm845_DB845c_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_sdm845_DB845c_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sdm845
	ln -sf ../../Qualcomm/sdm845/sdm845.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sdm845/DB845c.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_sdm845_LENOVO_81JL_LenovoYOGAC630_13Q50_LNVNB161216_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_sdm845_LENOVO_81JL_LenovoYOGAC630_13Q50_LNVNB161216_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sdm845
	ln -sf ../../Qualcomm/sdm845/Lenovo-YOGA-C630-13Q50.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sdm845/LENOVO-81JL-LenovoYOGAC630_13Q50-LNVNB161216.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_DB410c_DB410c_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_DB410c_DB410c_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/DB410c
	ln -sf ../../Qualcomm/apq8016-sbc/apq8016-sbc.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/DB410c/DB410c.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_sm8550_SM8550_HDK_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_sm8550_SM8550_HDK_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sm8550
	ln -sf ../../Qualcomm/sm8550/HDK/SM8550-HDK.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sm8550/SM8550-HDK.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_SC7180_sc7180_rt5682_max98357a_1mic_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_SC7180_sc7180_rt5682_max98357a_1mic_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/SC7180
	ln -sf ../../Qualcomm/sc7180/rt5682-max98357a/sc7180-rt5682-max98357a-1mic.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/SC7180/sc7180-rt5682-max98357a-1mic.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_SC7180_sc7180_adau7002_max98357a_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_SC7180_sc7180_adau7002_max98357a_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/SC7180
	ln -sf ../../Qualcomm/sc7180/adau7002-max98357a/sc7180-adau7002-max98357a.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/SC7180/sc7180-adau7002-max98357a.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_x1e80100_X1E001DE_DEVKIT_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_x1e80100_X1E001DE_DEVKIT_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/x1e80100
	ln -sf ../../Qualcomm/x1e80100/X1E001DE-DEVKIT.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/x1e80100/X1E001DE-DEVKIT.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_x1e80100_X1E80100_CRD_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_x1e80100_X1E80100_CRD_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/x1e80100
	ln -sf ../../Qualcomm/x1e80100/X1E80100-CRD.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/x1e80100/X1E80100-CRD.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_x1e80100_x1e80100_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_x1e80100_x1e80100_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/x1e80100
	ln -sf ../../Qualcomm/x1e80100/x1e80100.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/x1e80100/x1e80100.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_x1e80100_TUXEDO_TUXEDOElite14Gen1_2_0_TXEM14QX4NM_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_x1e80100_TUXEDO_TUXEDOElite14Gen1_2_0_TXEM14QX4NM_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/x1e80100
	ln -sf ../../Qualcomm/x1e80100/TUXEDO-Elite-14.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/x1e80100/TUXEDO-TUXEDOElite14Gen1-2.0-TXEM14QX4NM.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_x1e80100_X1E80100_EVK_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_x1e80100_X1E80100_EVK_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/x1e80100
	ln -sf ../../Qualcomm/x1e80100/X1E80100-EVK.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/x1e80100/X1E80100-EVK.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_qcs8300_MONACO_EVK_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_qcs8300_MONACO_EVK_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs8300
	ln -sf ../../Qualcomm/qcs8300/monaco-evk/MONACO-EVK.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs8300/MONACO-EVK.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_qcs8300_arduino_monza_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_qcs8300_arduino_monza_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs8300
	ln -sf ../../Qualcomm/qcs8300/arduino-monza/arduino-monza.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs8300/arduino-monza.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_qcs615_TALOS_EVK_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_qcs615_TALOS_EVK_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs615
	ln -sf ../../Qualcomm/qcs615/TALOS-EVK.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs615/TALOS-EVK.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_sa8775p_LEMANS_EVK_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_sa8775p_LEMANS_EVK_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sa8775p
	ln -sf ../../Qualcomm/sa8775p/lemans-evk/LEMANS-EVK.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sa8775p/LEMANS-EVK.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_qcm6490_QCM6490_IDP_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_qcm6490_QCM6490_IDP_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcm6490
	ln -sf ../../Qualcomm/qcm6490/QCM6490-IDP/QCM6490-IDP.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcm6490/QCM6490-IDP.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_kaanapali_Kaanapali_MTP_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_kaanapali_Kaanapali_MTP_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/kaanapali
	ln -sf ../../Qualcomm/kaanapali/MTP/Kaanapali-MTP.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/kaanapali/Kaanapali-MTP.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_sc8280xp_sc8280xp_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_sc8280xp_sc8280xp_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sc8280xp
	ln -sf ../../Qualcomm/sc8280xp/sc8280xp.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sc8280xp/sc8280xp.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_sm8250_Qualcomm_RB5_WSA8815_Speakers_DMIC0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_sm8250_Qualcomm_RB5_WSA8815_Speakers_DMIC0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sm8250
	ln -sf ../../Qualcomm/sm8250/Qualcomm-RB5-WSA8815-Speakers-DMIC0.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sm8250/Qualcomm-RB5-WSA8815-Speakers-DMIC0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_sm8650_SM8650_QRD_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_sm8650_SM8650_QRD_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sm8650
	ln -sf ../../Qualcomm/sm8650/QRD/SM8650-QRD.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sm8650/SM8650-QRD.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_sm8650_SM8650_MTP_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_sm8650_SM8650_MTP_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sm8650
	ln -sf ../../Qualcomm/sm8650/MTP/SM8650-MTP.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sm8650/SM8650-MTP.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_qcs6490_RadxaComputerCo_Ltd__RadxaDragonQ6A_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_qcs6490_RadxaComputerCo_Ltd__RadxaDragonQ6A_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs6490
	ln -sf QCS6490-Radxa-Dragon-Q6A.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs6490/RadxaComputerCo.Ltd.-RadxaDragonQ6A-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_qcs6490_QCS6490_Radxa_Dragon_Q6A_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_qcs6490_QCS6490_Radxa_Dragon_Q6A_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs6490
	ln -sf ../../Qualcomm/qcs6490/QCS6490-Radxa-Dragon-Q6A/QCS6490-Radxa-Dragon-Q6A.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs6490/QCS6490-Radxa-Dragon-Q6A.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_qcs6490_QCS6490_Thundercomm_RubikPi3_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_qcs6490_QCS6490_Thundercomm_RubikPi3_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs6490
	ln -sf ../../Qualcomm/qcs6490/QCS6490-Thundercomm-RubikPi3/QCS6490-Thundercomm-RubikPi3.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs6490/QCS6490-Thundercomm-RubikPi3.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_qcs6490_QCS6490_RB3Gen2_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_qcs6490_QCS6490_RB3Gen2_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs6490
	ln -sf ../../Qualcomm/qcs6490/QCS6490-RB3Gen2/QCS6490-RB3Gen2.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/qcs6490/QCS6490-RB3Gen2.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_apq8096_DB820c_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_apq8096_DB820c_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/apq8096
	ln -sf ../../Qualcomm/apq8096/apq8096.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/apq8096/DB820c.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_qualcomm_conf_d_DB820c_DB820c_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_qualcomm.mk
	@echo "Symlink: alsa_ucm_conf_qualcomm_conf_d_DB820c_DB820c_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/DB820c
	ln -sf ../../Qualcomm/apq8096/apq8096.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/DB820c/DB820c.conf
	touch $@

