# Auto-generated by gen_android_bp.py for usb-audio symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_usb-audio_conf_d_USB_Audio_USB_Audio_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_usb-audio.mk
	@echo "Symlink: alsa_ucm_conf_usb-audio_conf_d_USB_Audio_USB_Audio_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/USB-Audio
	ln -sf ../../USB-Audio/USB-Audio.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/USB-Audio/USB-Audio.conf
	touch $@

