# Auto-generated by gen_android_bp.py for sof-soundwire symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_sof-soundwire_sof_soundwire_cs35l56_cs42l43_spk_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_sof-soundwire.mk
	@echo "Symlink: alsa_ucm_conf_sof-soundwire_sof_soundwire_cs35l56_cs42l43_spk_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/sof-soundwire
	ln -sf cs42l43-spk.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/sof-soundwire/cs35l56+cs42l43-spk.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_sof-soundwire_sof_soundwire_cs42l43_spk_cs35l56_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_sof-soundwire.mk
	@echo "Symlink: alsa_ucm_conf_sof-soundwire_sof_soundwire_cs42l43_spk_cs35l56_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/sof-soundwire
	ln -sf cs42l43-spk.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/sof-soundwire/cs42l43-spk+cs35l56.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_sof-soundwire_conf_d_sof_soundwire_sof_soundwire_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_sof-soundwire.mk
	@echo "Symlink: alsa_ucm_conf_sof-soundwire_conf_d_sof_soundwire_sof_soundwire_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-soundwire
	ln -sf ../../sof-soundwire/sof-soundwire.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-soundwire/sof-soundwire.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_sof-soundwire_conf_d_amd_soundwire_amd_soundwire_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_sof-soundwire.mk
	@echo "Symlink: alsa_ucm_conf_sof-soundwire_conf_d_amd_soundwire_amd_soundwire_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/amd-soundwire
	ln -sf ../../sof-soundwire/sof-soundwire.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/amd-soundwire/amd-soundwire.conf
	touch $@

