# Auto-generated by gen_android_bp.py for intel symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_sof_skl_hda_card
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_sof_skl_hda_card"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d
	ln -sf sof-hda-dsp $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-skl_hda_card
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_SOF_SOF_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_SOF_SOF_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/SOF
	ln -sf ../../Intel/SOF/SOF.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/SOF/SOF.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_sof_glkda7219ma_sof_glkda7219ma_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_sof_glkda7219ma_sof_glkda7219ma_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-glkda7219ma
	ln -sf ../../Intel/sof-glkda7219max/sof-glkda7219max.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-glkda7219ma/sof-glkda7219ma.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_bytcr_rt5651_bytcr_rt5651_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_bytcr_rt5651_bytcr_rt5651_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/bytcr-rt5651
	ln -sf ../../Intel/bytcr-rt5651/bytcr-rt5651.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/bytcr-rt5651/bytcr-rt5651.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_dmic_Google_Cave_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_dmic_Google_Cave_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_dmic
	ln -sf ../../Intel/avs/avs_dmic/DMIC-2ch.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_dmic/Google-Cave-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_dmic_Google_Coral_rev2_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_dmic_Google_Coral_rev2_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_dmic
	ln -sf ../../Intel/avs/avs_dmic/DMIC-4ch.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_dmic/Google-Coral-rev2.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_dmic_HP_Soraka_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_dmic_HP_Soraka_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_dmic
	ln -sf ../../Intel/avs/avs_dmic/DMIC-2ch.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_dmic/HP-Soraka-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_dmic_Acer_Lars_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_dmic_Acer_Lars_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_dmic
	ln -sf ../../Intel/avs/avs_dmic/DMIC-2ch.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_dmic/Acer-Lars-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_dmic_Google_Atlas_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_dmic_Google_Atlas_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_dmic
	ln -sf ../../Intel/avs/avs_dmic/DMIC-4ch.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_dmic/Google-Atlas-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_dmic_Hewlett_Packard_Chell_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_dmic_Hewlett_Packard_Chell_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_dmic
	ln -sf ../../Intel/avs/avs_dmic/DMIC-2ch.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_dmic/Hewlett_Packard-Chell-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_chtmax98090_chtmax98090_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_chtmax98090_chtmax98090_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/chtmax98090
	ln -sf ../../Intel/chtmax98090/chtmax98090.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/chtmax98090/chtmax98090.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_sof_hda_dsp_sof_hda_dsp_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_sof_hda_dsp_sof_hda_dsp_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-hda-dsp
	ln -sf ../../Intel/sof-hda-dsp/sof-hda-dsp.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-hda-dsp/sof-hda-dsp.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_sof_hda_dsp_sof_skl_hda_card_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_sof_hda_dsp_sof_skl_hda_card_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-hda-dsp
	ln -sf ../../Intel/sof-hda-dsp/sof-hda-dsp.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-hda-dsp/sof-skl_hda_card.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_bdw_rt5677_bdw_rt5677_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_bdw_rt5677_bdw_rt5677_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/bdw-rt5677
	ln -sf ../../Intel/bdw-rt5677/bdw-rt5677.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/bdw-rt5677/bdw-rt5677.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_sof_essx8336_sof_essx8336_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_sof_essx8336_sof_essx8336_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-essx8336
	ln -sf ../../Intel/sof-essx8336/sof-essx8336.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-essx8336/sof-essx8336.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_sof_ehl_rt5660_sof_ehl_rt5660_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_sof_ehl_rt5660_sof_ehl_rt5660_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-ehl-rt5660
	ln -sf ../../Intel/sof-ehl-rt5660/sof-ehl-rt5660.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-ehl-rt5660/sof-ehl-rt5660.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_bytcht_es8316_bytcht_es8316_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_bytcht_es8316_bytcht_es8316_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/bytcht-es8316
	ln -sf ../../Intel/bytcht-es8316/bytcht-es8316.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/bytcht-es8316/bytcht-es8316.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_chtrt5645_chtrt5645_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_chtrt5645_chtrt5645_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/chtrt5645
	ln -sf ../../Intel/chtrt5645/chtrt5645.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/chtrt5645/chtrt5645.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_bytcht_cx2072x_bytcht_cx2072x_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_bytcht_cx2072x_bytcht_cx2072x_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/bytcht-cx2072x
	ln -sf ../../Intel/bytcht-cx2072x/bytcht-cx2072x.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/bytcht-cx2072x/bytcht-cx2072x.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_da7219_Google_Coral_rev2_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_da7219_Google_Coral_rev2_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_da7219
	ln -sf ../../Intel/avs/avs_da7219/avs_da7219.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_da7219/Google-Coral-rev2.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_da7219_Google_Atlas_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_da7219_Google_Atlas_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_da7219
	ln -sf ../../Intel/avs/avs_da7219/avs_da7219.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_da7219/Google-Atlas-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_bytcr_wm5102_bytcr_wm5102_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_bytcr_wm5102_bytcr_wm5102_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/bytcr-wm5102
	ln -sf ../../Intel/bytcr-wm5102/bytcr-wm5102.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/bytcr-wm5102/bytcr-wm5102.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_rt5663_Google_Eve_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_rt5663_Google_Eve_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_rt5663
	ln -sf ../../Intel/avs/avs_rt5663/Google-Eve-1.0.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_rt5663/Google-Eve-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_rt5663_HP_Soraka_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_rt5663_HP_Soraka_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_rt5663
	ln -sf ../../Intel/avs/avs_rt5663/HP-Soraka-1.0.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_rt5663/HP-Soraka-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_max98357a_Google_Cave_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_max98357a_Google_Cave_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_max98357a
	ln -sf ../../Intel/avs/avs_max98357a/avs_max98357a.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_max98357a/Google-Cave-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_max98357a_Google_Coral_rev2_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_max98357a_Google_Coral_rev2_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_max98357a
	ln -sf ../../Intel/avs/avs_max98357a/avs_max98357a.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_max98357a/Google-Coral-rev2.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_max98357a_Acer_Lars_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_max98357a_Acer_Lars_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_max98357a
	ln -sf ../../Intel/avs/avs_max98357a/avs_max98357a.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_max98357a/Acer-Lars-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_chtnau8824_chtnau8824_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_chtnau8824_chtnau8824_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/chtnau8824
	ln -sf ../../Intel/chtnau8824/chtnau8824.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/chtnau8824/chtnau8824.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_ssm4567_Hewlett_Packard_Chell_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_ssm4567_Hewlett_Packard_Chell_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_ssm4567
	ln -sf ../../Intel/avs/avs_ssm4567/Hewlett_Packard-Chell-1.0.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_ssm4567/Hewlett_Packard-Chell-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_nau8825_Google_Cave_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_nau8825_Google_Cave_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_nau8825
	ln -sf ../../Intel/avs/avs_nau8825/Google-Cave-1.0.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_nau8825/Google-Cave-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_nau8825_Acer_Lars_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_nau8825_Acer_Lars_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_nau8825
	ln -sf ../../Intel/avs/avs_nau8825/Acer-Lars-1.0.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_nau8825/Acer-Lars-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_nau8825_Hewlett_Packard_Chell_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_nau8825_Hewlett_Packard_Chell_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_nau8825
	ln -sf ../../Intel/avs/avs_nau8825/Hewlett_Packard-Chell-1.0.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_nau8825/Hewlett_Packard-Chell-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_cht_bsw_rt5672_cht_bsw_rt5672_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_cht_bsw_rt5672_cht_bsw_rt5672_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/cht-bsw-rt5672
	ln -sf ../../Intel/cht-bsw-rt5672/cht-bsw-rt5672.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/cht-bsw-rt5672/cht-bsw-rt5672.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_skylake_rt286_skylake_rt286_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_skylake_rt286_skylake_rt286_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/skylake-rt286
	ln -sf ../../Intel/skylake-rt286/skylake-rt286.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/skylake-rt286/skylake-rt286.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_rt5514_Google_Eve_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_rt5514_Google_Eve_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_rt5514
	ln -sf ../../Intel/avs/avs_rt5514/Google-Eve-1.0.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_rt5514/Google-Eve-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_max98373_Google_Atlas_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_max98373_Google_Atlas_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_max98373
	ln -sf ../../Intel/avs/avs_max98373/Google-Atlas-1.0.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_max98373/Google-Atlas-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_bytcr_rt5640_bytcr_rt5640_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_bytcr_rt5640_bytcr_rt5640_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/bytcr-rt5640
	ln -sf ../../Intel/bytcr-rt5640/bytcr-rt5640.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/bytcr-rt5640/bytcr-rt5640.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_max98927_Google_Eve_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_max98927_Google_Eve_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_max98927
	ln -sf ../../Intel/avs/avs_max98927/Google-Eve-1.0.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_max98927/Google-Eve-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_avs_max98927_HP_Soraka_1_0_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_avs_max98927_HP_Soraka_1_0_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_max98927
	ln -sf ../../Intel/avs/avs_max98927/HP-Soraka-1.0.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/avs_max98927/HP-Soraka-1.0.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_broxton_rt298_broxton_rt298_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_broxton_rt298_broxton_rt298_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/broxton-rt298
	ln -sf ../../Intel/broxton-rt298/broxton-rt298.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/broxton-rt298/broxton-rt298.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_kblrt5660_kblrt5660_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_kblrt5660_kblrt5660_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/kblrt5660
	ln -sf ../../Intel/kblrt5660/kblrt5660.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/kblrt5660/kblrt5660.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_hda_dsp_hda_dsp_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_hda_dsp_hda_dsp_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/hda-dsp
	ln -sf ../../Intel/hda-dsp/hda-dsp.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/hda-dsp/hda-dsp.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_hdaudioB0D2_hdaudioB0D2_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_hdaudioB0D2_hdaudioB0D2_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/hdaudioB0D2
	ln -sf ../../Intel/avs/hdaudioB0D2/hdaudioB0D2.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/hdaudioB0D2/hdaudioB0D2.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_broadwell_rt286_broadwell_rt286_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_broadwell_rt286_broadwell_rt286_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/broadwell-rt286
	ln -sf ../../Intel/broadwell-rt286/broadwell-rt286.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/broadwell-rt286/broadwell-rt286.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_intel_conf_d_chtrt5650_chtrt5650_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_intel.mk
	@echo "Symlink: alsa_ucm_conf_intel_conf_d_chtrt5650_chtrt5650_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/chtrt5650
	ln -sf ../../Intel/chtrt5650/chtrt5650.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/chtrt5650/chtrt5650.conf
	touch $@

