# Auto-generated by gen_android_bp.py for allwinner symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_allwinner_conf_d_sun4i_codec_h616_audio_codec_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_allwinner.mk
	@echo "Symlink: alsa_ucm_conf_allwinner_conf_d_sun4i_codec_h616_audio_codec_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sun4i-codec
	ln -sf ../../Allwinner/sun4i-h616/h616-audio-codec.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sun4i-codec/h616-audio-codec.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_allwinner_conf_d_simple_card_PinePhone_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_allwinner.mk
	@echo "Symlink: alsa_ucm_conf_allwinner_conf_d_simple_card_PinePhone_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card
	ln -sf ../../Allwinner/A64/PinePhone/PinePhone.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card/PinePhone.conf
	touch $@

