# Auto-generated by gen_android_bp.py for samsung symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_samsung_module_snd_soc_snow_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_samsung.mk
	@echo "Symlink: alsa_ucm_conf_samsung_module_snd_soc_snow_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module
	ln -sf ../Samsung/snow/snow.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module/snd_soc_snow.conf
	touch $@

