# Auto-generated by gen_android_bp.py for amlogic symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_amlogic_conf_d_gx_sound_card_LIBRETECH_CC_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_amlogic.mk
	@echo "Symlink: alsa_ucm_conf_amlogic_conf_d_gx_sound_card_LIBRETECH_CC_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/gx-sound-card
	ln -sf ../../Amlogic/p241/p241.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/gx-sound-card/LIBRETECH-CC.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_amlogic_conf_d_gx_sound_card_GXL_P241_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_amlogic.mk
	@echo "Symlink: alsa_ucm_conf_amlogic_conf_d_gx_sound_card_GXL_P241_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/gx-sound-card
	ln -sf ../../Amlogic/p241/p241.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/gx-sound-card/GXL-P241.conf
	touch $@

