# Auto-generated by gen_android_bp.py for io-boards symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_io-boards_conf_d_simple_card_apalis_nau8822_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_io-boards.mk
	@echo "Symlink: alsa_ucm_conf_io-boards_conf_d_simple_card_apalis_nau8822_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card
	ln -sf ../../IO-Boards/Toradex/apalis/eval.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card/apalis-nau8822.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_io-boards_conf_d_simple_card_verdin_nau8822_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_io-boards.mk
	@echo "Symlink: alsa_ucm_conf_io-boards_conf_d_simple_card_verdin_nau8822_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card
	ln -sf ../../IO-Boards/Toradex/verdin/dev.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card/verdin-nau8822.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_io-boards_conf_d_simple_card_aquila_wm8904_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_io-boards.mk
	@echo "Symlink: alsa_ucm_conf_io-boards_conf_d_simple_card_aquila_wm8904_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card
	ln -sf ../../IO-Boards/Toradex/aquila/dev.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card/aquila-wm8904.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_io-boards_conf_d_simple_card_tdx_smarc_wm8904_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_io-boards.mk
	@echo "Symlink: alsa_ucm_conf_io-boards_conf_d_simple_card_tdx_smarc_wm8904_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card
	ln -sf ../../IO-Boards/Toradex/smarc/dev.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card/tdx-smarc-wm8904.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_io-boards_conf_d_simple_card_verdin_wm8904_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_io-boards.mk
	@echo "Symlink: alsa_ucm_conf_io-boards_conf_d_simple_card_verdin_wm8904_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card
	ln -sf ../../IO-Boards/Toradex/verdin/dahlia.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card/verdin-wm8904.conf
	touch $@

