# Auto-generated by gen_android_bp.py for tegra symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_tegra_module_snd_soc_tegra_max98090_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_tegra.mk
	@echo "Symlink: alsa_ucm_conf_tegra_module_snd_soc_tegra_max98090_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module
	ln -sf ../Tegra/max98090/max98090.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module/snd_soc_tegra_max98090.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_tegra_module_snd_soc_tegra_alc5632_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_tegra.mk
	@echo "Symlink: alsa_ucm_conf_tegra_module_snd_soc_tegra_alc5632_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module
	ln -sf ../Tegra/alc5632/alc5632.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module/snd_soc_tegra_alc5632.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_tegra_conf_d_tegra_GoogleNyanBlaze_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_tegra.mk
	@echo "Symlink: alsa_ucm_conf_tegra_conf_d_tegra_GoogleNyanBlaze_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/tegra
	ln -sf ../../Tegra/max98090/max98090.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/tegra/GoogleNyanBlaze.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_tegra_conf_d_tegra_GoogleNyanBig_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_tegra.mk
	@echo "Symlink: alsa_ucm_conf_tegra_conf_d_tegra_GoogleNyanBig_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/tegra
	ln -sf ../../Tegra/max98090/max98090.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/tegra/GoogleNyanBig.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_tegra_conf_d_tegra_hda_tegra_hda_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_tegra.mk
	@echo "Symlink: alsa_ucm_conf_tegra_conf_d_tegra_hda_tegra_hda_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/tegra-hda
	ln -sf ../../Tegra/tegra-hda/tegra-hda.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/tegra-hda/tegra-hda.conf
	touch $@

