# Auto-generated by gen_android_bp.py for mediatek symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_mt8390_evk_mt8390_evk_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_mt8390_evk_mt8390_evk_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8390-evk
	ln -sf ../../MediaTek/mt8390-evk/mt8390-evk.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8390-evk/mt8390-evk.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_mt8183_da7219_r_mt8183_da7219_r_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_mt8183_da7219_r_mt8183_da7219_r_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8183_da7219_r
	ln -sf ../../MediaTek/mt8183/mt8183_da7219_rt1015p/mt8183_da7219_rt1015p.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8183_da7219_r/mt8183_da7219_r.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_mt8192_mt6359_mt8192_mt6359_rt1015p_rt5682_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_mt8192_mt6359_mt8192_mt6359_rt1015p_rt5682_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8192_mt6359
	ln -sf ../../MediaTek/mt8192/mt6359-rt1015p-rt5682/mt8192_mt6359_rt1015p_rt5682.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8192_mt6359/mt8192_mt6359_rt1015p_rt5682.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_mt8391_evk_mt8391_evk_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_mt8391_evk_mt8391_evk_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8391-evk
	ln -sf ../../MediaTek/mt8391-evk/mt8391-evk.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8391-evk/mt8391-evk.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_mt8183_mt6358_t_mt8183_mt6358_t_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_mt8183_mt6358_t_mt8183_mt6358_t_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8183_mt6358_t
	ln -sf ../../MediaTek/mt8183/mt8183_mt6358_ts3a227_max98357/mt8183_mt6358_ts3a227_max98357.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8183_mt6358_t/mt8183_mt6358_t.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_sof_mt8395_evk_sof_mt8395_evk_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_sof_mt8395_evk_sof_mt8395_evk_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-mt8395-evk
	ln -sf ../../MediaTek/sof-mt8395-evk/sof-mt8395-evk.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-mt8395-evk/sof-mt8395-evk.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_mt8365_evk_mt8365_evk_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_mt8365_evk_mt8365_evk_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8365-evk
	ln -sf ../../MediaTek/mt8365-evk/mt8365-evk.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8365-evk/mt8365-evk.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_mt8370_evk_mt8370_evk_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_mt8370_evk_mt8370_evk_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8370-evk
	ln -sf ../../MediaTek/mt8370-evk/mt8370-evk.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8370-evk/mt8370-evk.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_sof_mt8365_evk_sof_mt8365_evk_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_sof_mt8365_evk_sof_mt8365_evk_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-mt8365-evk
	ln -sf ../../MediaTek/mt8365-evk/sof/sof-mt8365-evk.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-mt8365-evk/sof-mt8365-evk.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_mt8366_evk_mt8366_evk_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_mt8366_evk_mt8366_evk_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8366-evk
	ln -sf ../../MediaTek/mt8366-evk/mt8366-evk.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8366-evk/mt8366-evk.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_sof_mt8196_nau8_sof_mt8196_nau8825_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_sof_mt8196_nau8_sof_mt8196_nau8825_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-mt8196-nau8
	ln -sf ../../MediaTek/mt8196-sof/nau8825-nau8318/sof-mt8196-nau8825-nau8318.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-mt8196-nau8/sof-mt8196-nau8825.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_mtk_rt5650_mtk_rt5650_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_mtk_rt5650_mtk_rt5650_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mtk-rt5650
	ln -sf ../../MediaTek/mtk-rt5650/mtk-rt5650.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mtk-rt5650/mtk-rt5650.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_mt8195_demo_mt8195_demo_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_mt8195_demo_mt8195_demo_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8195_demo
	ln -sf ../../MediaTek/mt8195_demo/mt8195_demo.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8195_demo/mt8195_demo.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_sof_mt8390_evk_sof_mt8390_evk_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_sof_mt8390_evk_sof_mt8390_evk_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-mt8390-evk
	ln -sf ../../MediaTek/mt8390-evk/sof/sof-mt8390-evk.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-mt8390-evk/sof-mt8390-evk.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_sof_m8195_r1019_sof_m8195_r1019_5682s_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_sof_m8195_r1019_sof_m8195_r1019_5682s_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-m8195_r1019
	ln -sf ../../MediaTek/mt8195-sof/mt6359-rt1019-rt5682/sof-mt8195-mt6359-rt1019-rt5682.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-m8195_r1019/sof-m8195_r1019_5682s.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_mt8395_evk_mt8395_evk_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_mt8395_evk_mt8395_evk_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8395-evk
	ln -sf ../../MediaTek/mt8395-evk/mt8395-evk.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/mt8395-evk/mt8395-evk.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_mediatek_conf_d_sof_mt8195_r101_sof_mt8195_r1019_5682_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_mediatek.mk
	@echo "Symlink: alsa_ucm_conf_mediatek_conf_d_sof_mt8195_r101_sof_mt8195_r1019_5682_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-mt8195_r101
	ln -sf ../../MediaTek/mt8195-sof/mt6359-rt1019-rt5682/sof-mt8195-mt6359-rt1019-rt5682.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/sof-mt8195_r101/sof-mt8195_r1019_5682.conf
	touch $@

