# Auto-generated by gen_android_bp.py for nxp symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_nxp_conf_d_simple_card_colibri_imx8x_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_nxp.mk
	@echo "Symlink: alsa_ucm_conf_nxp_conf_d_simple_card_colibri_imx8x_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card
	ln -sf ../../NXP/iMX8X/Toradex/colibri-imx8x/colibri-imx8x.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card/colibri-imx8x.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_nxp_conf_d_simple_card_colibri_imx7_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_nxp.mk
	@echo "Symlink: alsa_ucm_conf_nxp_conf_d_simple_card_colibri_imx7_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card
	ln -sf ../../NXP/iMX7/Toradex/colibri-imx7/colibri-imx7.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card/colibri-imx7.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_nxp_conf_d_simple_card_apalis_imx8qm_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_nxp.mk
	@echo "Symlink: alsa_ucm_conf_nxp_conf_d_simple_card_apalis_imx8qm_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card
	ln -sf ../../NXP/iMX8/Toradex/apalis-imx8/apalis-imx8.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card/apalis-imx8qm.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_nxp_conf_d_fsl_asoc_card_apalis_imx6_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_nxp.mk
	@echo "Symlink: alsa_ucm_conf_nxp_conf_d_fsl_asoc_card_apalis_imx6_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/fsl-asoc-card
	ln -sf ../../NXP/iMX6/Toradex/apalis-imx6/apalis-imx6.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/fsl-asoc-card/apalis-imx6.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_nxp_conf_d_fsl_asoc_card_colibri_imx6_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_nxp.mk
	@echo "Symlink: alsa_ucm_conf_nxp_conf_d_fsl_asoc_card_colibri_imx6_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/fsl-asoc-card
	ln -sf ../../NXP/iMX6/Toradex/colibri-imx6/colibri-imx6.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/fsl-asoc-card/colibri-imx6.conf
	touch $@

