# Auto-generated by gen_android_bp.py for omap symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_omap_module_snd_soc_omap_abe_twl6040_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_omap.mk
	@echo "Symlink: alsa_ucm_conf_omap_module_snd_soc_omap_abe_twl6040_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module
	ln -sf ../OMAP/abe-twl6040/abe-twl6040.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module/snd_soc_omap_abe_twl6040.conf
	touch $@

