# Auto-generated by gen_android_bp.py for common symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_common_codecs_cs35l56_cs42l43_spk
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_common.mk
	@echo "Symlink: alsa_ucm_conf_common_codecs_cs35l56_cs42l43_spk"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/codecs
	ln -sf cs42l43-spk+cs35l56 $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/codecs/cs35l56+cs42l43-spk
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_common_conf_d_acp_acp_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_common.mk
	@echo "Symlink: alsa_ucm_conf_common_conf_d_acp_acp_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp
	ln -sf ../../common/linked-card.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp/acp.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_common_conf_d_acp62_acp62_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_common.mk
	@echo "Symlink: alsa_ucm_conf_common_conf_d_acp62_acp62_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp62
	ln -sf ../../common/linked-card.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp62/acp62.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_common_conf_d_acp63_acp63_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_common.mk
	@echo "Symlink: alsa_ucm_conf_common_conf_d_acp63_acp63_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp63
	ln -sf ../../common/linked-card.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp63/acp63.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_common_conf_d_acp6x_acp6x_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_common.mk
	@echo "Symlink: alsa_ucm_conf_common_conf_d_acp6x_acp6x_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp6x
	ln -sf ../../common/linked-card.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp6x/acp6x.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_common_conf_d_acp_pdm_mach_acp_pdm_mach_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_common.mk
	@echo "Symlink: alsa_ucm_conf_common_conf_d_acp_pdm_mach_acp_pdm_mach_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp-pdm-mach
	ln -sf ../../common/linked-card.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/acp-pdm-mach/acp-pdm-mach.conf
	touch $@

