# Auto-generated by gen_android_bp.py for rockchip symlinks

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_rockchip_module_snd_soc_rockchip_max98090_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_rockchip.mk
	@echo "Symlink: alsa_ucm_conf_rockchip_module_snd_soc_rockchip_max98090_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module
	ln -sf ../Rockchip/max98090/max98090.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module/snd_soc_rockchip_max98090.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_rockchip_module_snd_soc_rk3399_gru_sound_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_rockchip.mk
	@echo "Symlink: alsa_ucm_conf_rockchip_module_snd_soc_rk3399_gru_sound_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module
	ln -sf ../Rockchip/rk3399-gru-sound/rk3399-gru-sound.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/module/snd_soc_rk3399_gru_sound.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_rockchip_conf_d_rk3588_es8316_rk3588_es8316_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_rockchip.mk
	@echo "Symlink: alsa_ucm_conf_rockchip_conf_d_rk3588_es8316_rk3588_es8316_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/rk3588-es8316
	ln -sf ../../Rockchip/rk3588-es8316/rk3588-es8316.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/rk3588-es8316/rk3588-es8316.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_rockchip_conf_d_simple_card_rockchip_es8316_codec_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_rockchip.mk
	@echo "Symlink: alsa_ucm_conf_rockchip_conf_d_simple_card_rockchip_es8316_codec_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card
	ln -sf ../../Rockchip/es8316/es8316.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card/rockchip,es8316-codec.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_rockchip_conf_d_simple_card_rk817_ext_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_rockchip.mk
	@echo "Symlink: alsa_ucm_conf_rockchip_conf_d_simple_card_rk817_ext_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card
	ln -sf ../../Rockchip/rk817-sound/rk817-sound.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card/rk817_ext.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_rockchip_conf_d_simple_card_rk817_int_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_rockchip.mk
	@echo "Symlink: alsa_ucm_conf_rockchip_conf_d_simple_card_rk817_int_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card
	ln -sf ../../Rockchip/rk817-sound/rk817-sound.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/simple-card/rk817_int.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_rockchip_conf_d_rk3399_gru_soun_rk3399_gru_soun_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_rockchip.mk
	@echo "Symlink: alsa_ucm_conf_rockchip_conf_d_rk3399_gru_soun_rk3399_gru_soun_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/rk3399-gru-soun
	ln -sf ../../Rockchip/rk3399-gru-sound/rk3399-gru-sound.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/rk3399-gru-soun/rk3399-gru-soun.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_rockchip_conf_d_VEYRON_I2S_VEYRON_I2S_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_rockchip.mk
	@echo "Symlink: alsa_ucm_conf_rockchip_conf_d_VEYRON_I2S_VEYRON_I2S_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/VEYRON-I2S
	ln -sf ../../Rockchip/max98090/max98090.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/VEYRON-I2S/VEYRON-I2S.conf
	touch $@

include $(CLEAR_VARS)
LOCAL_MODULE := alsa_ucm_conf_rockchip_conf_d_rockchip_es8316_rockchip_es8316_conf
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_TAGS := optional
include $(BUILD_SYSTEM)/base_rules.mk
$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/Android_rockchip.mk
	@echo "Symlink: alsa_ucm_conf_rockchip_conf_d_rockchip_es8316_rockchip_es8316_conf"
	mkdir -p $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/rockchip_es8316
	ln -sf ../../Rockchip/es8316/es8316.conf $(TARGET_OUT_VENDOR)/usr/share/alsa/ucm2/conf.d/rockchip_es8316/rockchip_es8316.conf
	touch $@

